export const FUN_FACTS = [
  'Octopuses have three hearts! 🐙',
  'Honey never spoils — 3000-year-old honey has been found still edible! 🍯',
  "A group of flamingos is called a 'flamboyance'! 🦩",
  'Bananas are berries, but strawberries are not! 🍌',
  'Sharks are older than trees! 🦈',
  'A day on Venus is longer than its year! 🪐',
  'Honeybees can recognize human faces! 🐝',
  'A bolt of lightning is hotter than the surface of the sun! ⚡',
  'Sea otters hold hands while sleeping so they don\'t drift apart! 🦦',
  'The Eiffel Tower can grow taller in summer heat! 🗼',
  'Wombats poop in cube shapes! 🟫',
  'Your nose can remember 50,000 different scents! 👃',
  'A group of crows is called a "murder"! 🐦‍⬛',
  'It rains diamonds on Jupiter and Saturn! 💎',
  'Butterflies taste with their feet! 🦋',
  'Cows have best friends and can become stressed when they are separated! 🐄',
  'A snail can have thousands of tiny teeth! 🐌',
  'Penguins propose to their mates by giving them pebbles! 🐧',
  'Some turtles can breathe through their bottoms! 🐢',
  'A group of owls is called a "parliament"! 🦉',
  'Sea stars can regrow lost arms! ⭐',
  'The heart of a shrimp is located in its head! 🦐',
  'Goats have rectangular pupils in their eyes! 🐐',
  'Ravens can imitate human speech! 🐦‍⬛',
  'Elephants can communicate using sounds too low for humans to hear! 🐘',
  'Some frogs can freeze during winter and thaw out alive in spring! 🐸',
  'Koalas have fingerprints that look surprisingly similar to human fingerprints! 🐨',
  'A group of giraffes is called a "tower"! 🦒',
  'Dolphins have names for one another! 🐬',
  'The fingerprints of a koala are so similar to humans that they can be difficult to tell apart! 🐨',
  'Sloths can hold their breath for a surprisingly long time by slowing their heartbeat! 🦥',
  'A group of zebras is called a "dazzle"! 🦓',
  'Cheetahs cannot roar, but they can purr! 🐆',
  'Some bamboo can grow more than 30 inches in a single day! 🎋',
  'The fingerprints of every person are different, even identical twins! 👆',
  'Your brain uses about as much energy as a small light bulb! 🧠',
  'A bolt of lightning can travel from cloud to ground in just a fraction of a second! ⚡',
  'There are more possible ways to shuffle a deck of cards than there are atoms on Earth! 🃏',
  'Space is completely silent because sound needs a medium like air to travel! 🚀',
  'The Moon has moonquakes! 🌙',
  'A group of dolphins is called a "pod"! 🐬',
  'Octopuses can change the color and texture of their skin to hide! 🐙',
  'A blue whale is the largest animal ever known to have lived! 🐋',
  'Some cats can rotate their ears nearly 180 degrees! 🐱',
  'Polar bears have black skin underneath their white fur! 🐻‍❄️',
  'A hummingbird is the only bird that can fly backward! 🐦',
  'Frogs drink water through their skin instead of their mouths! 🐸',
  'An ostrich has eyes bigger than its brain! 🪶',
  'Butterflies were once caterpillars! 🦋',
  'A group of rabbits is called a "fluffle"! 🐇',
  'Camels have three sets of eyelids to protect their eyes from sand! 🐪',
  'Armadillos can hold their breath for several minutes! 🦔',
  'Some spiders can travel through the air using silk! 🕷️',
  'A giraffe has the same number of neck bones as a human — just seven! 🦒',
  'Pineapples can take around two years to grow! 🍍',
  'Apples float in water because about one-quarter of their volume is air! 🍎',
  'A group of pandas is sometimes called an "embarrassment"! 🐼',
  'Jellyfish have been living in Earth’s oceans for hundreds of millions of years! 🌊',
  'The tongue of a blue whale can weigh as much as an elephant! 🐋',
  'Some lizards can detach their tails to escape predators! 🦎',
  'A kangaroo cannot walk backward easily because of its large tail and body shape! 🦘',
  'Mosquitoes are attracted to carbon dioxide that we breathe out! 🦟',
  'The smallest mammal in the world is the bumblebee bat! 🦇',
  'A group of lions is called a "pride"! 🦁',
  'The Earth is not a perfect sphere — it is slightly wider around the middle! 🌍',
];

export const QUOTES = [
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'Success is the sum of small efforts, repeated day in and day out.', author: 'Robert Collier' },
  { text: 'It always seems impossible until it is done.', author: 'Nelson Mandela' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
  { text: 'Believe you can and you are halfway there.', author: 'Theodore Roosevelt' },
  { text: 'You learn something every day if you pay attention.', author: 'Ray LeBlond' },
  { text: 'A little progress each day adds up to big results.', author: 'Unknown' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes' },
  { text: 'Mistakes are proof that you are trying.', author: 'Unknown' },
  { text: 'Every accomplishment starts with the decision to try.', author: 'John F. Kennedy' },
  { text: 'The only way to learn mathematics is to do mathematics.', author: 'Paul Halmos' },
  { text: 'Learning never exhausts the mind.', author: 'Leonardo da Vinci' },
  { text: 'Knowledge is power.', author: 'Francis Bacon' },
  { text: 'Great things are done by a series of small things brought together.', author: 'Vincent van Gogh' },
  { text: 'Success is the result of preparation, hard work, and learning from failure.', author: 'Colin Powell' },
  { text: 'The roots of education are bitter, but the fruit is sweet.', author: 'Aristotle' },
  { text: 'Every child is an artist. The problem is how to remain an artist once we grow up.', author: 'Pablo Picasso' },
  { text: 'The beautiful thing about learning is that you can learn something new every day.', author: 'Unknown' },
  { text: 'Do not be afraid to give up the good to go for the great.', author: 'John D. Rockefeller' },
  { text: 'What we learn with pleasure we never forget.', author: 'Alfred Mercier' },
  { text: 'The journey of a thousand miles begins with one step.', author: 'Lao Tzu' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
  { text: 'I have not failed. I have just found 10,000 ways that will not work.', author: 'Thomas Edison' },
  { text: 'If you can dream it, you can do it.', author: 'Walt Disney' },
  { text: 'The harder you work for something, the greater you will feel when you achieve it.', author: 'Unknown' },
  { text: 'Do not let what you cannot do interfere with what you can do.', author: 'John Wooden' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'Every day is a new opportunity to learn something amazing.', author: 'Unknown' },
  { text: 'The best way to predict your future is to create it.', author: 'Abraham Lincoln' },
  { text: 'Dream big and dare to fail.', author: 'Norman Vaughan' },
  { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
  { text: 'Nothing is impossible. The word itself says, “I am possible!”', author: 'Audrey Hepburn' },
  { text: 'Keep your face always toward the sunshine, and shadows will fall behind you.', author: 'Walt Whitman' },
  { text: 'You do not have to be great to start, but you have to start to be great.', author: 'Zig Ziglar' },
  { text: 'The more you practice, the better you become.', author: 'Unknown' }
];

export function getRandomEntry(excludeText) {
  const pool = [
    ...FUN_FACTS.map((text) => ({ type: 'fact', text })),
    ...QUOTES.map((q) => ({ type: 'quote', text: q.text, author: q.author })),
  ];
  const choices = pool.filter((p) => p.text !== excludeText);
  return choices[Math.floor(Math.random() * choices.length)];
}
